import type { Command } from "commander";

import { confirm } from "../../core/prompts/confirm.js";
import type {
  PostgresCsvExportOptions,
  PostgresDirectScriptOptions,
} from "../../services/index.js";
import {
  exportPostgresCsvDataset,
  generatePostgresDirectScript,
  writeCommandLog,
} from "../../services/index.js";
import {
  createPostgresCsvExportProgressReporter,
  createPostgresDirectScriptProgressReporter,
  printPostgresCsvExportSummary,
  printPostgresDirectScriptSummary,
} from "../ui/output.js";

export function registerPostgresCommands(program: Command): void {
  const postgres = program
    .command("postgres")
    .description(
      "PostgreSQL-oriented helpers for hybrid loading and database operations.",
    );

  postgres
    .command("generate-script")
    .argument(
      "<input>",
      "Path to the sanitized dataset directory generated by cnpj-db-loader sanitize.",
    )
    .option(
      "--output <path>",
      "Custom output directory for the generated psql script and manifest.",
    )
    .option(
      "--dataset <dataset>",
      "Generate a script only for one dataset block, for example establishments or companies.",
    )
    .option(
      "--script-name <name>",
      "Generated psql script file name. Defaults to import-postgres-direct.sql.",
    )
    .option(
      "--source-encoding <encoding>",
      "PostgreSQL client encoding used while reading sanitized Receita files. Defaults to UTF8.",
    )
    .option(
      "--transaction-mode <mode>",
      "Transaction mode for generated scripts: single, phase or none. Defaults to single.",
    )
    .option(
      "--include <items>",
      "Comma-separated steps to include: domains,companies,establishments,partners,simples,secondary-cnaes,indexes,analyze.",
    )
    .option("--skip-indexes", "Do not generate the indexes step.")
    .option("--skip-analyze", "Do not generate the analyze step.")
    .option("-f, --force", "Skip the confirmation prompt.")
    .description(
      "Generate a direct psql import script that loads sanitized Receita files without rewriting them into new CSV files.",
    )
    .action(
      async (
        input: string,
        options: {
          output?: string;
          dataset?: string;
          scriptName?: string;
          sourceEncoding?: string;
          transactionMode?: string;
          include?: string;
          skipIndexes?: boolean;
          skipAnalyze?: boolean;
          force?: boolean;
        },
      ) => {
        if (!options.force) {
          const confirmed = await confirm(
            `Generate a direct PostgreSQL psql import script from ${input}? This command does not rewrite the source files; it creates only a SQL script and manifest.`,
          );
          if (!confirmed) {
            console.log("PostgreSQL direct script generation cancelled.");
            return;
          }
        }

        const progress = createPostgresDirectScriptProgressReporter();
        const generateOptions: PostgresDirectScriptOptions = {
          onProgress: progress,
        };

        if (options.output) {
          generateOptions.outputPath = options.output;
        }

        if (options.dataset) {
          generateOptions.dataset =
            options.dataset as PostgresDirectScriptOptions["dataset"];
        }

        if (options.scriptName) {
          generateOptions.scriptName = options.scriptName;
        }

        if (options.sourceEncoding) {
          generateOptions.sourceEncoding = options.sourceEncoding;
        }

        if (options.transactionMode) {
          generateOptions.transactionMode =
            options.transactionMode as PostgresDirectScriptOptions["transactionMode"];
        }

        if (options.include) {
          generateOptions.include = options.include
            .split(",")
            .map((item) => item.trim())
            .filter(Boolean) as PostgresDirectScriptOptions["include"];
        }

        if (options.skipIndexes) {
          generateOptions.skipIndexes = true;
        }

        if (options.skipAnalyze) {
          generateOptions.skipAnalyze = true;
        }

        const summary = await generatePostgresDirectScript(
          input,
          generateOptions,
        );
        const logFilePath = await writeCommandLog(
          "postgres-generate-script",
          summary,
        );
        printPostgresDirectScriptSummary(summary, logFilePath);
      },
    );

  postgres
    .command("export-csv")
    .argument(
      "<input>",
      "Path to the sanitized or validated extracted dataset directory.",
    )
    .option(
      "--output <path>",
      "Custom output directory for PostgreSQL-ready CSV files.",
    )
    .option(
      "--dataset <dataset>",
      "Export only one dataset block, for example establishments or companies.",
    )
    .option(
      "--script-name <name>",
      "Generated psql script file name. Defaults to import-postgres-direct.sql.",
    )
    .option("-f, --force", "Skip the confirmation prompt.")
    .description(
      "Convert sanitized Receita files into real PostgreSQL-ready CSV files and generate a direct psql import script.",
    )
    .action(
      async (
        input: string,
        options: {
          output?: string;
          dataset?: string;
          scriptName?: string;
          force?: boolean;
        },
      ) => {
        if (!options.force) {
          const confirmed = await confirm(
            `Export PostgreSQL-ready CSV files from ${input}? This command creates normalized CSV files and a generated psql import script.`,
          );
          if (!confirmed) {
            console.log("PostgreSQL CSV export cancelled.");
            return;
          }
        }

        const progress = createPostgresCsvExportProgressReporter();
        const exportOptions: PostgresCsvExportOptions = {
          onProgress: progress,
        };

        if (options.output) {
          exportOptions.outputPath = options.output;
        }

        if (options.dataset) {
          exportOptions.dataset =
            options.dataset as PostgresCsvExportOptions["dataset"];
        }

        if (options.scriptName) {
          exportOptions.scriptName = options.scriptName;
        }

        const summary = await exportPostgresCsvDataset(input, exportOptions);
        const logFilePath = await writeCommandLog(
          "postgres-export-csv",
          summary,
        );
        printPostgresCsvExportSummary(summary, logFilePath);
      },
    );
}
